title = "Radical Ideas"
languageCode = "en-us"
baseurl = "https://sauravmodak.com/"
theme = "paperback"

[params]
# your name to display by the copyright sign
# default: undefined
AuthorName = "Saurav Modak"

# tagline to show beneath homepage h1
# default: undefined
Tagline = "My Ideas Blog"

# number of posts to show on index
# default: 10
HomepagePosts = 10

# if set to true, social links will be displayed in the footer
# default: undefined
SocialLinks = true

# default: undefined
GithubUsername = "uniquerockrz"

# default: undefined
TwitterUsername = "SauravModak"
